"""Centralized color palette and styling constants for visualization."""


class Theme:
    """Single source of truth for all visualization colors and styles."""

    # --- Shared palette ---
    SOFT_GREEN_FILL = "#d5e8d4"
    SOFT_GREEN_BORDER = "#82b366"
    SOFT_BLUE_FILL = "#dae8fc"
    SOFT_BLUE_BORDER = "#6c8ebf"
    SOFT_RED_FILL = "#f8cecc"
    SOFT_RED_BORDER = "#b85450"
    SOFT_GOLD_FILL = "#fff2cc"
    SOFT_GOLD_BORDER = "#d6b656"
    SOFT_PURPLE_FILL = "#e1d5e7"
    SOFT_PURPLE_BORDER = "#9673a6"
    SOFT_PINK_FILL = "#f8d7da"
    SOFT_PINK_BORDER = "#c0392b"
    LIGHT_GRAY_FILL = "#ecf0f1"
    LIGHT_GRAY_BORDER = "#95a5a6"
    MUTED_GRAY = "#636e72"
    MUTED_GRAY_DARK = "#7f8c8d"
    DARK_TEXT = "#2d3436"
    CLUSTER_BG = "#f9f9f9"
    WHITE = "#ffffff"

    # --- State machine ---
    SM_INITIAL_FILL = SOFT_GREEN_FILL
    SM_INITIAL_BORDER = SOFT_GREEN_BORDER
    SM_NORMAL_FILL = SOFT_BLUE_FILL
    SM_NORMAL_BORDER = SOFT_BLUE_BORDER
    SM_FINAL_FILL = SOFT_RED_FILL
    SM_FINAL_BORDER = SOFT_RED_BORDER
    SM_HIGHLIGHT_FILL = SOFT_GOLD_FILL
    SM_HIGHLIGHT_BORDER = SOFT_GOLD_BORDER
    SM_EDGE_DEFAULT = DARK_TEXT
    SM_EDGE_EVENT = DARK_TEXT
    SM_INTERNAL_EDGE = MUTED_GRAY_DARK

    # --- Publishing ---
    PUB_PUBLISHER_FILL = SOFT_GREEN_FILL
    PUB_PUBLISHER_BORDER = SOFT_GREEN_BORDER
    PUB_EVENT_FILL = SOFT_BLUE_FILL
    PUB_EVENT_BORDER = SOFT_BLUE_BORDER
    PUB_EMPTY_FILL = LIGHT_GRAY_FILL
    PUB_EMPTY_BORDER = LIGHT_GRAY_BORDER
    PUB_EDGE_PUBLISH = SOFT_GREEN_BORDER
    PUB_EDGE_LABEL = MUTED_GRAY

    # --- Listening ---
    LISTEN_LISTENER_FILL = SOFT_BLUE_FILL
    LISTEN_LISTENER_BORDER = SOFT_BLUE_BORDER
    LISTEN_CALLBACK_FILL = SOFT_GREEN_FILL
    LISTEN_CALLBACK_BORDER = SOFT_GREEN_BORDER
    LISTEN_PUBLISHER_FILL = SOFT_PURPLE_FILL
    LISTEN_PUBLISHER_BORDER = SOFT_PURPLE_BORDER
    LISTEN_EMPTY_FILL = LIGHT_GRAY_FILL
    LISTEN_EMPTY_BORDER = LIGHT_GRAY_BORDER
    LISTEN_EDGE_CALLS = SOFT_BLUE_BORDER
    LISTEN_EDGE_PUBLISHES = SOFT_PURPLE_BORDER
    LISTEN_EDGE_LABEL = MUTED_GRAY

    # --- Agent (comprehensive) ---
    AGENT_COMPONENT_FILL = SOFT_GOLD_FILL
    AGENT_COMPONENT_BORDER = SOFT_GOLD_BORDER
    AGENT_CLUSTER_SM_BORDER = SOFT_RED_BORDER
    AGENT_CLUSTER_SM_BG = CLUSTER_BG
    AGENT_CLUSTER_PUB_BORDER = SOFT_GREEN_BORDER
    AGENT_CLUSTER_PUB_BG = CLUSTER_BG
    AGENT_CLUSTER_LISTEN_BORDER = SOFT_BLUE_BORDER
    AGENT_CLUSTER_LISTEN_BG = CLUSTER_BG
    AGENT_CLUSTER_COMP_BORDER = SOFT_GOLD_BORDER
    AGENT_CLUSTER_COMP_BG = CLUSTER_BG
    AGENT_CLUSTER_LABEL = MUTED_GRAY

    # --- Cross-agent ---
    CROSS_AGENT_FILL = SOFT_PINK_FILL
    CROSS_AGENT_BORDER = SOFT_PINK_BORDER
    CROSS_EVENT_EDGE = "#27ae60"
    CROSS_EVENT_LABEL = "#1e8449"
    CROSS_PARENT_CHILD_EDGE = "#8e44ad"
    CROSS_EXTERNAL_FILL = LIGHT_GRAY_FILL
    CROSS_EXTERNAL_BORDER = LIGHT_GRAY_BORDER
    CROSS_SELF_EDGE = "#2980b9"

    # --- Default edge styling ---
    SM_EDGE_START_COLOR = SOFT_GREEN_BORDER
    SM_EDGE_START_STYLE = "dashed"
    SM_EDGE_STOP_COLOR = SOFT_RED_BORDER
    SM_EDGE_STOP_STYLE = "dashed"
